# Generated by Django 6.0.7 on 2026-07-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="ID of the device that originated the event",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("motion_detected", "motion_detected"),
                            ("intrusion_alert", "intrusion_alert"),
                            ("camera_offline", "camera_offline"),
                        ],
                        help_text="Event type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        help_text="Event severity classification",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Date/time of event occurrence, given by the originating device"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(help_text="Optional event metadata", null=True),
                ),
            ],
        ),
    ]
